import { useState } from 'react';
import { Helmet } from 'react-helmet-async';
import Header from '@/components/Header';
import MobileNav from '@/components/MobileNav';
import Footer from '@/components/Footer';
import { useLanguage } from '@/lib/i18n';

const faqItems = [
  { q: 'sb.fq1', a: 'sb.fa1' },
  { q: 'sb.fq2', a: 'sb.fa2' },
  { q: 'sb.fq3', a: 'sb.fa3' },
  { q: 'sb.fq4', a: 'sb.fa4' },
  { q: 'sb.fq5', a: 'sb.fa5' },
  { q: 'sb.fq6', a: 'sb.fa6' },
];

const features = [
  { title: 'sb.f1t', desc: 'sb.f1d', icon: <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"/></svg> },
  { title: 'sb.f2t', desc: 'sb.f2d', icon: <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg> },
  { title: 'sb.f3t', desc: 'sb.f3d', icon: <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M8 3H7a2 2 0 00-2 2v5a2 2 0 01-2 2 2 2 0 012 2v5c0 1.1.9 2 2 2h1"/><path d="M16 3h1a2 2 0 012 2v5a2 2 0 002 2 2 2 0 00-2 2v5a2 2 0 01-2 2h-1"/></svg> },
  { title: 'sb.f4t', desc: 'sb.f4d', icon: <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="M21 15l-5-5L5 21"/></svg> },
  { title: 'sb.f5t', desc: 'sb.f5d', icon: <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="8" width="3" height="12" rx="1"/><rect x="10" y="4" width="3" height="16" rx="1"/><rect x="17" y="10" width="3" height="10" rx="1"/></svg> },
  { title: 'sb.f6t', desc: 'sb.f6d', icon: <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="6" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="6" r="3"/><path d="M6 9v6M18 9a3 3 0 010 6"/></svg> },
];

const steps = [
  { step: '01', title: 'sb.sp1t', desc: 'sb.sp1d' },
  { step: '02', title: 'sb.sp2t', desc: 'sb.sp2d' },
  { step: '03', title: 'sb.sp3t', desc: 'sb.sp3d' },
  { step: '04', title: 'sb.sp4t', desc: 'sb.sp4d' },
];

const failureModes = [
  { problem: 'sb.fm1p', title: 'sb.fm1t', desc: 'sb.fm1d', solution: 'sb.fm1s', solDesc: 'sb.fm1sd' },
  { problem: 'sb.fm2p', title: 'sb.fm2t', desc: 'sb.fm2d', solution: 'sb.fm2s', solDesc: 'sb.fm2sd' },
  { problem: 'sb.fm3p', title: 'sb.fm3t', desc: 'sb.fm3d', solution: 'sb.fm3s', solDesc: 'sb.fm3sd' },
];

const traderCards = [
  { title: 'sb.n1t', desc: 'sb.n1d', icon: <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="4" y="4" width="16" height="16" rx="2"/><path d="M9 9h6M9 13h6M9 17h4"/></svg> },
  { title: 'sb.n2t', desc: 'sb.n2d', icon: <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M17 1l4 4-4 4"/><path d="M3 11V9a4 4 0 014-4h14"/><path d="M7 23l-4-4 4-4"/><path d="M21 13v2a4 4 0 01-4 4H3"/></svg> },
  { title: 'sb.n3t', desc: 'sb.n3d', icon: <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><polyline points="23 4 23 10 17 10"/><path d="M20.49 15a9 9 0 11-2.12-9.36L23 10"/></svg> },
];

const stats = [
  { value: '1,600+', label: 'sb.st1' },
  { value: '7', label: 'sb.st2' },
  { value: '10 min', label: 'sb.st3' },
  { value: '24/7', label: 'sb.st4' },
];

const codeExample = `// RSI + MACD crossover strategy
// Generated by Tradvio AI - editable

const config = {
  rsiPeriod: 14,
  rsiOversold: 30,
  macdFast: 12,
  macdSlow: 26,
  macdSignal: 9,
  stopLossPct: 2,
  takeProfitPct: 4,
};

function onCandle(candle, state) {
  const rsi = td.indicators.rsi(candle, config.rsiPeriod);
  const macd = td.indicators.macd(
    candle, config.macdFast, config.macdSlow, config.macdSignal
  );

  const macdBullishCross =
    macd.histogram > 0 && state.prevHistogram <= 0;
  state.prevHistogram = macd.histogram;

  if (rsi < config.rsiOversold && macdBullishCross) {
    const stopLoss = candle.close * (1 - config.stopLossPct / 100);
    const takeProfit = candle.close * (1 + config.takeProfitPct / 100);

    td.buy({
      allocation: 100,
      stopLoss,
      takeProfit,
      reason: 'RSI oversold + MACD bullish crossover',
    });
  }
}`;

export default function AIStrategyBuilder() {
  const { t } = useLanguage();
  const [mobileNavOpen, setMobileNavOpen] = useState(false);

  return (
    <>
      <Helmet>
        <title>{t('meta.builder')}</title>
        <meta name="description" content="Describe your strategy in plain English. Tradvio AI writes the code, backtests it instantly, and deploys it live. No coding required. Free to start." />
        <meta name="robots" content="index, follow" />
        <link rel="canonical" href="https://tradvioai.com/ai-strategy-builder/" />
      </Helmet>

      <Header onMenuToggle={() => setMobileNavOpen(true)} />
      <MobileNav isOpen={mobileNavOpen} onClose={() => setMobileNavOpen(false)} />

      <main id="main-content" className="pt-nav">
        {/* ═══════════ HERO ═══════════ */}
        <section className="relative py-20 md:py-28 bg-deep overflow-hidden">
          <div className="absolute w-[600px] h-[600px] rounded-full blur-[100px] pointer-events-none opacity-30 bg-[radial-gradient(circle,rgba(220,38,38,0.3),transparent_70%)] -top-[150px] -right-[150px]" />
          <div className="absolute w-[400px] h-[400px] rounded-full blur-[80px] pointer-events-none opacity-20 bg-[radial-gradient(circle,rgba(220,38,38,0.2),transparent_70%)] bottom-0 -left-[100px]" />

          <div className="max-w-7xl mx-auto px-6 relative z-10">
            <div className="grid lg:grid-cols-2 gap-14 items-center">
              {/* Left - copy */}
              <div>
                <h1 className="text-[clamp(2.4rem,5vw,4.4rem)] font-bold leading-[1.05] -tracking-[0.02em] mb-5">
                  {t('sb.h1a')}<br />
                  <span className="text-accent">{t('sb.h1b')}</span>
                </h1>
                <p className="text-lg text-muted-dark leading-relaxed mb-8 max-w-[500px]">
                  {t('sb.heroBody')}
                </p>
                <div className="flex gap-3 flex-wrap mb-6">
                  <a href="/get-started/" className="btn btn-primary btn-lg">{t('sb.cta1')}</a>
                  <a href="#how-it-works" className="btn btn-secondary btn-lg">{t('sb.cta2')}</a>
                </div>
                <div className="flex items-center gap-4 text-xs text-ink-soft">
                  <span className="inline-flex items-center gap-1.5"><span className="w-1.5 h-1.5 rounded-full bg-success" /> {t('sb.p1')}</span>
                  <span className="inline-flex items-center gap-1.5"><span className="w-1.5 h-1.5 rounded-full bg-success" /> {t('sb.p2')}</span>
                  <span className="inline-flex items-center gap-1.5"><span className="w-1.5 h-1.5 rounded-full bg-success" /> {t('sb.p3')}</span>
                </div>
              </div>

              {/* Right - Chat mockup */}
              <div className="bg-navy border border-border rounded-2xl overflow-hidden shadow-[0_30px_70px_-20px_rgba(0,0,0,0.5)]">
                <div className="bg-medium-navy border-b border-border px-4 py-3 flex items-center justify-between">
                  <span className="text-[0.7rem] font-semibold text-ink-soft uppercase tracking-wider">{t('sb.chatTitle')}</span>
                  <span className="text-[0.6rem] text-success font-bold">● {t('sb.online')}</span>
                </div>
                <div className="p-5 space-y-4">
                  {/* User message */}
                  <div className="flex justify-end">
                    <div className="bg-accent text-white rounded-xl rounded-tr-sm px-4 py-3 text-sm max-w-[85%]">
                      {t('sb.userMsg')}
                    </div>
                  </div>
                  {/* AI message */}
                  <div className="flex justify-start">
                    <div className="bg-deep border border-border rounded-xl rounded-tl-sm px-4 py-3 text-sm max-w-[85%]">
                      <div className="flex items-center gap-2 mb-2">
                        <span className="w-6 h-6 rounded-md bg-accent/15 text-accent flex items-center justify-center font-mono font-bold text-[0.6rem]">AI</span>
                        <span className="font-semibold text-ink">{t('sb.aiTitle')}</span>
                      </div>
                      <p className="text-ink-soft text-xs leading-relaxed">
                        {t('sb.aiMsg1')} <span className="font-mono text-accent">rsi_macd_btc.py</span>. {t('sb.aiMsg2')}
                      </p>
                    </div>
                  </div>
                  {/* Code preview */}
                  <div className="bg-deep border border-border rounded-xl p-4">
                    <div className="flex items-center justify-between mb-2">
                      <span className="font-mono text-[0.65rem] text-ink-soft">rsi_macd_btc.py</span>
                      <span className="text-[0.6rem] text-success font-bold">✓ {t('sb.validated')}</span>
                    </div>
                    <pre className="font-mono text-[0.62rem] text-ink-soft leading-relaxed overflow-x-auto whitespace-pre">{codeExample}</pre>
                  </div>
                  {/* Backtest summary */}
                  <div className="bg-deep border border-border rounded-xl p-4 grid grid-cols-3 gap-3">
                    <div className="text-center">
                      <div className="font-mono text-lg font-bold text-success">+32.5%</div>
                      <div className="text-[0.6rem] text-ink-soft uppercase tracking-wider mt-0.5">{t('sb.btl1')}</div>
                    </div>
                    <div className="text-center">
                      <div className="font-mono text-lg font-bold text-ink">64.2%</div>
                      <div className="text-[0.6rem] text-ink-soft uppercase tracking-wider mt-0.5">{t('sb.btl2')}</div>
                    </div>
                    <div className="text-center">
                      <div className="font-mono text-lg font-bold text-danger">-11.4%</div>
                      <div className="text-[0.6rem] text-ink-soft uppercase tracking-wider mt-0.5">{t('sb.btl3')}</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ═══════════ AI WITH RAILS ═══════════ */}
        <section className="py-24 bg-navy border-y border-border">
          <div className="max-w-7xl mx-auto px-6">
            <div className="text-center mb-14">
              <div className="text-xs font-semibold uppercase tracking-[0.14em] text-accent mb-3">{t('sb.railsEyebrow')}</div>
              <h2 className="text-[clamp(2rem,4vw,3.4rem)] font-bold leading-[1.1] -tracking-[0.02em] mb-4">
                {t('sb.rails1')}<br />
                <span className="text-ink-soft font-light italic">{t('sb.rails2')}</span>
              </h2>
            </div>

            <div className="space-y-6">
              {failureModes.map((f) => (
                <div key={f.title} className="grid md:grid-cols-2 gap-0 border border-border rounded-2xl overflow-hidden">
                  <div className="p-6 bg-deep">
                    <div className="text-[0.62rem] uppercase tracking-[0.12em] text-danger font-bold mb-2">{t(f.problem)}</div>
                    <h3 className="text-lg font-semibold mb-2">{t(f.title)}</h3>
                    <p className="text-sm text-muted-dark leading-relaxed">{t(f.desc)}</p>
                  </div>
                  <div className="p-6 bg-deep border-t md:border-t-0 md:border-l border-border">
                    <div className="text-[0.62rem] uppercase tracking-[0.12em] text-success font-bold mb-2">{t(f.solution)}</div>
                    <p className="text-sm text-muted-dark leading-relaxed">{t(f.solDesc)}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ═══════════ FEATURES ═══════════ */}
        <section className="py-24 bg-deep">
          <div className="max-w-7xl mx-auto px-6">
            <div className="text-center mb-14">
              <div className="text-xs font-semibold uppercase tracking-[0.14em] text-accent mb-3">{t('sb.ftEyebrow')}</div>
              <h2 className="text-[clamp(2rem,4vw,3.4rem)] font-bold leading-[1.1] -tracking-[0.02em]">
                {t('sb.ft1')}<br />
                <span className="text-ink-soft font-light italic">{t('sb.ft2')}</span>
              </h2>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              {features.map((f) => (
                <div key={f.title} className="bg-navy border border-border rounded-xl p-6 hover:border-accent/30 transition-colors group">
                  <div className="w-11 h-11 rounded-xl bg-accent/10 flex items-center justify-center mb-4 text-accent group-hover:bg-accent group-hover:text-white transition-colors">{f.icon}</div>
                  <h3 className="text-lg font-semibold mb-2 group-hover:text-accent transition-colors">{t(f.title)}</h3>
                  <p className="text-sm text-muted-dark leading-relaxed">{t(f.desc)}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ═══════════ HOW IT WORKS ═══════════ */}
        <section id="how-it-works" className="py-24 bg-navy border-y border-border">
          <div className="max-w-7xl mx-auto px-6">
            <div className="text-center mb-14">
              <div className="text-xs font-semibold uppercase tracking-[0.14em] text-accent mb-3">{t('sb.hiwEyebrow')}</div>
              <h2 className="text-[clamp(2rem,4vw,3.4rem)] font-bold leading-[1.1] -tracking-[0.02em] mb-4">
                {t('sb.hiw1')}<br />
                <span className="text-ink-soft font-light italic">{t('sb.hiw2')}</span>
              </h2>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 relative">
              <div className="absolute top-10 left-[8%] right-[8%] h-px bg-border hidden lg:block" />
              {steps.map((s) => (
                <div key={s.step} className="relative z-10 text-center">
                  <div className="w-20 h-20 mx-auto mb-5 rounded-full bg-accent text-white flex items-center justify-center font-mono text-lg font-bold shadow-[0_0_24px_rgba(220,38,38,0.3)]">
                    {s.step}
                  </div>
                  <h3 className="text-lg font-semibold mb-2">{t(s.title)}</h3>
                  <p className="text-sm text-muted-dark leading-relaxed">{t(s.desc)}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ═══════════ BUILT FOR EVERY TRADER ═══════════ */}
        <section className="py-24 bg-deep">
          <div className="max-w-7xl mx-auto px-6">
            <div className="text-center mb-14">
              <div className="text-xs font-semibold uppercase tracking-[0.14em] text-accent mb-3">{t('sb.ewEyebrow')}</div>
              <h2 className="text-[clamp(2rem,4vw,3.4rem)] font-bold leading-[1.1] -tracking-[0.02em]">
                {t('sb.ew1')}<br />
                <span className="text-ink-soft font-light italic">{t('sb.ew2')}</span>
              </h2>
            </div>

            <div className="grid md:grid-cols-3 gap-6">
              {traderCards.map((b) => (
                <div key={b.title} className="bg-navy border border-border rounded-xl p-6 text-center">
                  <div className="w-11 h-11 mx-auto mb-4 rounded-xl bg-accent/10 flex items-center justify-center text-accent">
                    {b.icon}
                  </div>
                  <h3 className="font-semibold text-ink mb-2">{t(b.title)}</h3>
                  <p className="text-sm text-muted-dark leading-relaxed">{t(b.desc)}</p>
                </div>
              ))}
            </div>

            {/* Stats */}
            <div className="mt-10 grid grid-cols-2 md:grid-cols-4 gap-px bg-border border border-border rounded-xl overflow-hidden max-w-4xl mx-auto">
              {stats.map((s) => (
                <div key={s.label} className="bg-navy py-6 px-4 text-center">
                  <div className="text-2xl font-bold text-accent">{s.value}</div>
                  <div className="text-xs text-ink-soft mt-1.5">{t(s.label)}</div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ═══════════ FAQ ═══════════ */}
        <section className="py-24 bg-navy border-y border-border">
          <div className="max-w-7xl mx-auto px-6">
            <div className="text-center mb-14">
              <div className="text-xs font-semibold uppercase tracking-[0.14em] text-accent mb-3">{t('sb.faqEyebrow')}</div>
              <h2 className="text-[clamp(2rem,4vw,3.4rem)] font-bold leading-[1.1] -tracking-[0.02em]">
                {t('sb.faq1')}<br />
                <span className="text-ink-soft font-light italic">{t('sb.faq2')}</span>
              </h2>
            </div>

            <div className="max-w-[760px] mx-auto space-y-3">
              {faqItems.map((item, i) => (
                <details key={i} className="bg-deep border border-border rounded-xl p-5 group" open={i === 0}>
                  <summary className="cursor-pointer font-semibold text-[15.5px] text-ink list-none flex justify-between items-center">
                    {t(item.q)}
                    <span className="font-mono text-lg text-accent ml-4 flex-shrink-0 group-open:hidden">+</span>
                    <span className="font-mono text-lg text-accent ml-4 flex-shrink-0 hidden group-open:block">–</span>
                  </summary>
                  <p className="mt-3 text-sm text-muted-dark leading-relaxed">{t(item.a)}</p>
                </details>
              ))}
            </div>
          </div>
        </section>

        {/* ═══════════ CTA ═══════════ */}
        <section className="py-[100px] text-center bg-deep relative overflow-hidden">
          <div className="absolute w-[700px] h-[700px] rounded-full bg-[radial-gradient(circle,rgba(220,38,38,0.08),transparent_60%)] top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 pointer-events-none" />
          <div className="max-w-[640px] mx-auto px-6 relative z-10">
            <h2 className="text-[clamp(2rem,4vw,3.4rem)] font-bold leading-[1.1] -tracking-[0.02em] mb-5">
              {t('sb.close1')}<br />
              <span className="text-accent">{t('sb.close2')}</span>
            </h2>
            <p className="text-lg text-muted-dark mb-8">
              {t('sb.closeSub')}
            </p>
            <a href="/get-started/" className="btn btn-primary btn-lg">{t('sb.closeCta')}</a>
            <p className="text-xs text-ink-soft mt-6 max-w-[480px] mx-auto leading-relaxed">
              {t('sb.closeNote')}
            </p>
          </div>
        </section>
      </main>

      <Footer />
    </>
  );
}
